# Generated by Django 5.0 on 2023-12-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="item",
            name="currency",
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
